From: Erwin Harte
Subject: [DGD] Re: DGD http daemon?
Date: Wed Feb  9 16:25:01 2005

On Wed, Feb 09, 2005 at 12:38:59AM -0800, Christopher Allen wrote:
[...]
> A different issue is interface in a web world. You should take a look at the
> Zealous and Alice clients that we use at Skotos -- try out Castle Marrach
> (free trial) using IE (for Alice) or Mozilla/Firebird (for Zealous) to see

You mean Firefox, its most recent incarnation. ;)  Zealous also works
with Netscape 7.2 (and newer, I would assume).

Cheers,

Erwin.
-- 
Erwin Harte
