From: dgd at list.imaginary.com (Christopher Allen)
Date: Sun Feb  2 12:38:06 2003
Subject: Re[2]: [DGD] Impressed with DGD

"Christopher Darque":
> If this game I am
> considering is proposed, and accepted, at Skotos then this
> might be a real possibility.

If you are considering a game for us, either using your own library (as
WAP does with Grendel's Revenge and TEC) or Skotos' own library (which
is used by Castle Marrach), then you'll have access to our clients
(ActiveX, Java, and Mozilla Javascript) which all use HTML font tags for
color inside the text window.

You can specify any color you want using hex codes, but the following
are the default named ones:

{ "black",    0x000000 },
{ "white",    0xffffff },
{ "green",    0x00ff00 },
{ "maroon",   0x800000 },
{ "olive",    0x008000 },
{ "navy",     0x000080 },
{ "purple",   0x800080 },
{ "gray",     0x808080 },
{ "red",      0xff0000 },
{ "yellow",   0xffff00 },
{ "blue",     0x0000ff },
{ "teal",     0x008080 },
{ "lime",     0x808000 },
{ "aqua",     0x00ffff },
{ "fuchsia",  0xff00ff },
{ "silver",   0xc0c0c0 },

In addition, the Alice ActiveX client supports some (but not all) of the
Pueblo commands:

        <br/>COMPLETELY FUNCTIONAL MARKUP
        <xch_page clear=text />
        <body bgcolor=silver text=black alink=red vlink=red link=red />
        <hr/>
        <br/>Testing xch_page clear=text Tag.
        <br/>Testing body Tag.
        <br/>Testing Header Rule.
        <br/>Testing img img xch_mode=text Tag <img xch_mode=text/>.
        <br/>Testing img img xch_mode=purehtml Tag <img
xch_mode=purehtml/>.
        <br/>Testing img img xch_mode=html Tag <img xch_mode=html/>.
        <br/>Testing bgcolor & text & *link Attributes in body Tag.
       <br/>Testing xch_mudtext <xch_mudtext>I'm using
Alice</xch_mudtext>
        <br/>Testing xch_cmd Attribute <a xch_cmd="scratch my
ring">Scratch me</a>.
        <br/>
        <br/>Pueblo Forms Test:
        <form method=xch_cmd >
                <br/><select name=sourceselect>
<option>Select 1</option>
<option selected>Select 2</option>
<option>Select 3</option>
<option>Select 4</option>
<option>Select 5</option>
<option>Select 6</option>
</select>
<br/><textarea name=sourcetextarea rows=5 cols=30 />
        <br/><input type=checkbox checked name=sourcecheckbox
value=checkbox />Checkbox 1
        <br/><input type=radio checked name=sourceradio
value=radio />Radio 1
        <br/><input type=number name=sourcenumber size=6
maxlength=6 />Number 1
        <br/><input type=text name=sourcetext size=12
maxlength=12 />Text 1
        <br/><input type=password name=sourcepassword size=12
maxlength=12 />Password 1
        <br/><input type=submit value="Send" />
        <br/><input type=reset value="Reset" />
        </form>
        <br/>Character Editing Elements:
        <br/>Testing <b>Bold</b>.
        <br/>Testing <i>Italic</i>.
        <br/>Testing <u>Underline</u>.
        <br/>Testing <strike>Strike</strike>.
        <br/>Testing <strong>Strong</strong>.
        <br/>Testing <em>Emphasis</em>.
        <br/>Testing <cite>Cite</cite>.
        <br/>Testing <tt>Typewriter</tt>.
        <br/>Testing <code>Code</code>.
        <br/>Testing <samp>Samp</samp>.
        <br/>
        <br/>Block Formatting Elements:
        <br/>Testing Header Rule:
<hr size=4 width=50% align=center />
        <br/>Testing Headers:
        <h1>Header 1</h1>
        <h2>Header 2</h2>
        <h3>Header 3</h3>
        <h4>Header 4</h4>
        <h5>Header 5</h5>
        <h6>Header 6</h6>
        <br/><quote>Quote: The quick brown fox jumped over the lazy dog.
The quick brown fox jumped over the lazy dog. The quick brown fox jumped
over the lazy dog. </quote>
        <address>Address: The quick brown fox jumped over the lazy dog.
The quick brown fox jumped over the lazy dog. The quick brown fox jumped
over the lazy dog.</address>
        <blockquote>Blockquote: The quick brown fox jumped over the lazy
dog. The quick brown fox jumped over the lazy dog. The quick brown fox
jumped over the lazy dog.</blockquote>
        Testing Ordered List:<ol>
       <li>List Item One</li>
       <li>List Item Two</li>
       </ol>
Testing Unordered List:<ul>
       <li>List Item One</li>
       <li>List Item Two</li>
       </ul>
Testing Directory List:<dir>
       <li>List Item One</li>
       <li>List Item Two</li>
       </dir>
Testing Menu List:<menu>
       <li>List Item One</li>
       <li>List Item Two</li>
       </menu>
Testing Definition List<dl>
<dt>definition term</dt>
       <dd>definition data</dd>
       </dl>
        Testing Font Color <font color=aqua>aqua</font>.
       <br/>Testing Font Color <font color=black>black</font>.
       <br/>Testing Font Color <font color=blue>blue</font>.
       <br/>Testing Font Color <font color=fuchsia>fuchsia</font>.
       <br/>Testing Font Color <font color=gray>gray</font>.
       <br/>Testing Font Color <font color=green>green</font>.
       <br/>Testing Font Color <font color=lime>lime</font>.
       <br/>Testing Font Color <font color=maroon>maroon</font>.
       <br/>Testing Font Color <font color=navy>navy</font>.
       <br/>Testing Font Color <font color=olive>olive</font>.
       <br/>Testing Font Color <font color=purple>purple</font>.
       <br/>Testing Font Color <font color=red>red</font>.
       <br/>Testing Font Color <font color=silver>silver</font>.
       <br/>Testing Font Color <font color=teal>teal</font>.
       <br/>Testing Font Color <font color=white>white</font>.
       <br/>Testing Font Color <font color=yellow>yellow</font>.
       <br/>Testing Font Multiset <font fgcolor=red bgcolor=white
size="+3">Test</font>.
        <br/>PARTIALLY FUNCTIONAL MARKUP
       <br/>Testing Paragraph Tags:
<br/><nobr>Testing Nobr. The quick brown fox jumped over the
lazy dog. The quick brown fox jumped over the lazy dog. The quick brown
fox jumped over the lazy dog. The quick brown fox jumped over the lazy
dog.</nobr>
<br/><base>Testing Base. The quick brown fox jumped over the
lazy dog. The quick brown fox jumped over the lazy dog. The quick brown
fox jumped over the lazy dog. The quick brown fox jumped over the lazy
dog.</base>
<br/><xmp>Testing Xmp. The quick brown fox jumped over the lazy
dog. The quick brown fox jumped over the lazy dog. The quick brown fox
jumped over the lazy dog. The quick brown fox jumped over the lazy
dog.</xmp>
<br/><listing>Testing Listing. The quick brown fox jumped over
the lazy dog. The quick brown fox jumped over the lazy dog. The quick
brown fox jumped over the lazy dog. The quick brown fox jumped over the
lazy dog.</listing>
<br/><plaintext>Testing Plaintext. The quick brown fox jumped
over the lazy dog. The quick brown fox jumped over the lazy dog. The
quick brown fox jumped over the lazy dog. The quick brown fox jumped
over the lazy dog.</plaintext>
<br/><pre>Testing Pre. The quick brown fox jumped over the lazy
dog. The quick brown fox jumped over the lazy dog. The quick brown fox
jumped over the lazy dog. The quick brown fox jumped over the lazy
dog.</pre>
        <hr/>
        NOT-FUNCTIONAL PUEBLO MARKUP
        <br/>Testing Font Color <font color=grey>grey</font>.
        <br/>Testing Font Color <font color=brown>brown</font>.
        <br/>Testing send Tag <send>touch my ring</send>.
        <br/>Testing xch_pane Tag <xch_pane action=open name=map
xch_panetitle="Map of the City" options="floating persistent fit
nonsizeable" vspace=5 hspace=5/>
        <br/>Testing xch_pane Tag <xch_pane action=open name=buttonbar
options="fit internal" align=bottom href="test.html"/>
        <br/>Testing href Attribute <a href="test" >Click me</a>.
        <br/>Testing img Tag <img src="test" />.
        <br/>Testing img Tag <img src=\$prop(this.img-url) />.
        <br/>Testing img img xch_alert Tag <img xch_alert/>.
        <br/>Testing xch_hint Attributes for xch_cmd links <a
xch_cmd="scratch my ring" xch_hint="scratch my ring">Scratch me</a>.
        <br/>Testing link vlink alink Attributes for xch_cmd links <a
xch_cmd="scratch my ring" link=red alink=red vlink=red >Scratch me</a>.
        <br/>Testing text Attributes for xch_cmd links <a
xch_cmd="scratch my ring" text=red >Scratch me</a>.
        <br/>Testing color Tag <color fore=green back=black > Green on
Black </color>.
        <hr/>

You can also send special SKOOT commands that will command the clients
to execute Javascript in the window that the client resides in.

The Marrach game uses colors (see the command PROFILE to set default
colours) and some the Pueblo specific tags (see the command EXITS).
Grendel's Revenge makes most use of the SKOOT commands. To see these
features you will need to be using our ActiveX client on Internet
Explorer.

-- Christopher Allen

------------------------------------------------------------------------
.. Christopher Allen                                 Skotos Tech Inc. ..
..                           1512 Walnut St., Berkeley, CA 94709-1513 ..
.. <http://www.skotos.net>           o510/647-2760x202  f510/647-2761 ..
