From: dgd at list.imaginary.com (Par Winzell)
Date: Fri Oct 24 09:06:01 2003
Subject: [DGD] dgd crashes on fatal errors

> IMHO this is a bug. Even if the driver should go down on a fatal error, it
> should not go down in flames :) 

I'm pointlessly writing to agree with what Felix has already said. The
driver object is LPC at the lowest level, and DGD is correct to expect
consistency from it. Dumping core is not 'going down in flames', it's
just not high-level cuddly.

Zell
