From: dgd at list.imaginary.com (Felix A. Croes)
Date: Thu Mar 21 12:14:01 2002
Subject: [DGD] Printing out nil?

Jay Shaffstall wrote:

> >When you find out what makes the difference between crashing and not
> >crashing, please let me know.  DGD should never crash.
>
>[...]
> Not sure what you can do in DGD about this type of thing, since it's 
> impossible to tell the difference between infinite recursion and a 
> recursion that simply isn't finished yet (at least until you run out of 
> stack space).

This is indeed the one case where a crash may "naturally" occur.

Regards,
Dworkin
