From: dgd@dworkin.nl (Par Winzell)
Date: Tue May 31 20:20:01 2005
Subject: [DGD] LPC parsing in DGD

Shaun deRost Vantuil wrote:

> Does DGD compile LPC for use later on, or does it parse the code every time 
> the LPC is run? I hope Im making sense here. 

DGD compiles the LPC (once) to bytecode, which it interprets at runtime.
It's pretty fast. It is also capable of compiling the LPC to C in an
offline process. The resulting code is even faster.

Zell
