This MUD comes with ABSOLUTELY NO WARRANTY;
for details, type "help warranty" after login.
The server is public domain and you are welcome
to redistribute it under certain conditions;
Type "help copying" for details.


                     The Seas of Night

         A Collaborative Story of Postmortem Piracy
                 Upon the Highest of Seas

                    and, simultaneously,

             A Multiplayer Environment Built upon
                the Phantasmal MUD Library

Your account name: 