This MUD comes with ABSOLUTELY NO WARRANTY;
for details, type "help warranty" after login.
The server is public domain and you are welcome
to redistribute it under certain conditions;
Type "help copying" for details.

This is a Phantasmal-based MUD.  See
"http://phantasmal.sf.net" for details.

The owners of this MUD can customize this file.
It's located in /usr/game/text/welcome.msg.  But
they haven't done so yet.

Enter Account Name or Close Connection Now

Account Login: 
