DM BETA v0.0001
Copyright (C) 2000-2001 Noah Gibbs
DM BETA comes with ABSOLUTELY NO WARRANTY;
for details, type "help warranty" after login.
The server is free software and you are welcome
to redistribute it under certain conditions;
Type "help copying" for details.

Registered or adventurous users ONLY
Not for general consumption
External Use Only

Enter Account Name or Close Connection Now

Account Login: 